SENDLE_EVENT_MAP = {"LABEL_CREATED":"LABEL_CREATED","PICKUP":"PICKED_UP","IN_TRANSIT":"IN_TRANSIT","OUT_FOR_DELIVERY":"OUT_FOR_DELIVERY","DELIVERED":"DELIVERED","EXCEPTION":"EXCEPTION"}
ALT_EVENT_MAP = {"CREATED":"LABEL_CREATED","COLLECTED":"PICKED_UP","TRANSIT":"IN_TRANSIT","OFD":"OUT_FOR_DELIVERY","DELIVERED":"DELIVERED","EXCEPTION":"EXCEPTION"}
AUSPOST_EVENT_MAP = {"CREATED":"LABEL_CREATED","ACCEPTED":"PICKED_UP","IN_TRANSIT":"IN_TRANSIT","OFD":"OUT_FOR_DELIVERY","DELIVERED":"DELIVERED","EXCEPTION":"EXCEPTION"}

def canonicalize(provider: str, event_code: str) -> str:
    code = (event_code or "").strip().upper()
    if provider == "SENDLE":
        return SENDLE_EVENT_MAP.get(code, "EXCEPTION")
    if provider == "ALT":
        return ALT_EVENT_MAP.get(code, "EXCEPTION")
    if provider == "AUSPOST":
        return AUSPOST_EVENT_MAP.get(code, "EXCEPTION")
    return "EXCEPTION"
